# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chat_list.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ListBox(object):
    def setupUi(self, ListBox):
        ListBox.setObjectName("ListBox")
        ListBox.resize(450, 80)
        ListBox.setMinimumSize(QtCore.QSize(450, 80))
        ListBox.setMaximumSize(QtCore.QSize(450, 80))
        self.widget = QtWidgets.QWidget(ListBox)
        self.widget.setGeometry(QtCore.QRect(0, 0, 450, 80))
        self.widget.setMinimumSize(QtCore.QSize(450, 80))
        self.widget.setMaximumSize(QtCore.QSize(450, 80))
        self.widget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(0, 3, 73, 73))
        self.label.setStyleSheet("")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../ui_img/koprofil.png"))
        self.label.setScaledContents(True)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(84, 17, 141, 25))
        font = QtGui.QFont()
        font.setFamily("G마켓 산스 TTF Medium")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(85, 43, 291, 16))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(94, 94, 94);")
        self.label_3.setObjectName("label_3")
        self.chat_time = QtWidgets.QLabel(self.widget)
        self.chat_time.setGeometry(QtCore.QRect(378, 19, 61, 16))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.chat_time.setFont(font)
        self.chat_time.setStyleSheet("color: rgb(94, 94, 94);")
        self.chat_time.setObjectName("chat_time")

        self.retranslateUi(ListBox)
        QtCore.QMetaObject.connectSlotsByName(ListBox)

    def retranslateUi(self, ListBox):
        _translate = QtCore.QCoreApplication.translate
        ListBox.setWindowTitle(_translate("ListBox", "ListBox"))
        self.label_2.setText(_translate("ListBox", "박호현"))
        self.label_3.setText(_translate("ListBox", "안녕하세요~"))
        self.chat_time.setText(_translate("ListBox", "오후 5:28"))
